### ISSUE TITLE
Technical Viability: Unclear decision model for matching algorithm -artist to casting directors suggestions

### ISSUE THREAD

**Issue by apoorvabanubakodesjsu** [SJSUFall2019-CMPE272/Tara-A-place-where-talent-meets-opportunity#5]
Though the technical stack is explained in detail with focus on front end and backend: no details of actual decision process are mentioned,
Example: How do you match artists to the casting directors? Which algorithms are you planning to use to give an effective match?
Without an efficient skill to requirement matching model, the product even with such strong backend and frontend tech stack doesn’t provide enough value if matching algorithm isn't able to suggest best of the crowd matches.

**Comment by Chaitanyadasari** [comment]
We are suggesting the match based on the skill set and the requirement as mentioned by the recruiter. We'll be saving the values and we are not doing any match the Talent and the Recruiter who likes the other profile will do the match.
